schema_version = "1.0.0"

id = "vrm"
version = "2.20.54"
name = "VRM format"
tagline = "VRM import, export and editing capabilities"
maintainer = "Isamu Mogi <dyob@lunaport.net>"
type = "add-on"

website = "https://vrm-addon-for-blender.info"

tags = ["Import-Export", "Animation", "Modeling", "Material", "Physics"]

blender_version_min = "2.93.0"
blender_version_max = "4.1.999"

license = ["SPDX:MIT"]

copyright = [
  "2020 Isamu Mogi",
  "2018 iCyP",
]

[permissions]
files = "Import/export VRM from/to disk"
