schema_version = "1.0.0"

id = "vrm"
version = "3.19.2"

name = "KHR Character / VRM format"
tagline = "Import, export, and editing functions for VRM format and experimental KHR Character format."
maintainer = "Isamu Mogi <dyob@lunaport.net>"
type = "add-on"

website = "https://vrm-addon-for-blender.info"

tags = ["Import-Export", "Animation", "Modeling", "Material", "Physics"]

blender_version_min = "4.2.0"
blender_version_max = "5.1.0"

license = ["SPDX:MIT", "SPDX:GPL-3.0-or-later"]

copyright = [
  "2020 Isamu Mogi",
  "2018 iCyP",
]

[permissions]
files = "Import/export KHR Character/VRM from/to disk"
