name: benchmark

permissions: {}

on:
  push:
    branches:
      - main
      - ci-benchmark
  pull_request:
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ubuntu-24.04
    timeout-minutes: 720
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get update -q
          sudo DEBIAN_FRONTEND=noninteractive apt-get install \
            build-essential \
            ca-certificates \
            cmake \
            cmake-curses-gui \
            cmake-gui patch \
            curl \
            git \
            git-lfs \
            libboost-dev \
            libdbus-1-dev \
            libdecor-0-dev \
            libegl-dev \
            libembree-dev \
            libepoxy-dev \
            libfftw3-dev \
            libfreetype-dev \
            libgl-dev \
            libgmp-dev \
            libopenexr-dev \
            libosd-dev \
            libpng-dev \
            libpugixml-dev \
            libpython3-dev \
            libshaderc-dev \
            libtbb-dev \
            libtiff-dev \
            libvulkan-dev \
            libwayland-dev \
            libx11-dev \
            libxcursor-dev \
            libxi-dev \
            libxinerama-dev \
            libxkbcommon-dev \
            libxrandr-dev \
            libxxf86vm-dev \
            libzstd-dev \
            ninja-build \
            pybind11-dev \
            subversion \
            wayland-protocols \
            xz-utils \
            --no-install-recommends --yes
      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          # For reasons unknown, flamegraphs cannot be generated with Codspeed unless Python is
          # installed via actions/setup-python.
          python-version: "3.12.12"
      - run: pip3 install "numpy < 3" "requests < 3" "zstandard < 1" "pytest < 10" "pytest-codspeed < 5"
      - run: echo /opt/vrm/lib | sudo tee /etc/ld.so.conf.d/vrm.conf
      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        id: cache
        with:
          path: benchmark-dependencies.tar.gz
          key: benchmark-dependencies-${{ runner.os }}-${{ hashFiles('tools/install_ci_codspeed_dependencies.sh') }}
      - if: steps.cache.outputs.cache-hit == 'true'
        run: tar xzf benchmark-dependencies.tar.gz -C /opt
      - if: steps.cache.outputs.cache-hit != 'true'
        run: ./tools/install_ci_codspeed_dependencies.sh
      - run: sudo ldconfig
      - run: |
          export PYTHONPATH="${PWD}/src:/opt/vrm/lib/python3.12/site-packages"
          echo "PYTHONPATH=${PYTHONPATH}" >>"$GITHUB_ENV"
          python3 -c 'import bpy; assert(bpy.app.version == (4, 5, 4))'
      - uses: CodSpeedHQ/action@4348f634fa7309fe23aac9502e88b999ec90a164 # v4.3.1
        with:
          mode: instrumentation
          run: pytest --codspeed || true
          working-directory: benchmarks
