name: benchmark

permissions: {}

on:
  push:
    branches:
      - main
      - ci-benchmark
  pull_request:
  workflow_dispatch:

jobs:
  prepare-benchmark:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    if: ${{ github.repository_visibility == 'public' }}
    timeout-minutes: 720
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: ./.github/actions/prepare-benchmark

  benchmark:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    needs: prepare-benchmark
    timeout-minutes: 720
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: ./.github/actions/prepare-benchmark
        id: prepare-benchmark
        with:
          require-cache: true
      - uses: CodSpeedHQ/action@208425962c215de49ed713e18c4b9bde9bda5c52 # v4.10.2
        env:
          PYTHONPATH: "${{ github.workspace }}/src:${{ steps.prepare-benchmark.outputs.PYTHONPATH }}"
        with:
          mode: simulation
          run: pytest src/ --codspeed || true
          working-directory: benchmarks
