name: benchmark-next

permissions: {}

on:
  push:
    branches:
      - main
      - ci-benchmark
  pull_request:
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get update -q
          sudo DEBIAN_FRONTEND=noninteractive apt-get install \
            build-essential \
            ca-certificates \
            cmake \
            cmake-curses-gui \
            cmake-gui patch \
            curl \
            git \
            git-lfs \
            libboost-dev \
            libdbus-1-dev \
            libdecor-0-dev \
            libegl-dev \
            libembree-dev \
            libepoxy-dev \
            libfftw3-dev \
            libfreetype-dev \
            libgl-dev \
            libgmp-dev \
            libopenexr-dev \
            libosd-dev \
            libpng-dev \
            libpugixml-dev \
            libpython3-dev \
            libshaderc-dev \
            libtbb-dev \
            libtiff-dev \
            libvulkan-dev \
            libwayland-dev \
            libx11-dev \
            libxcursor-dev \
            libxi-dev \
            libxinerama-dev \
            libxkbcommon-dev \
            libxrandr-dev \
            libxxf86vm-dev \
            libzstd-dev \
            ninja-build \
            pybind11-dev \
            python3 \
            python3-numpy \
            python3-venv \
            python3-requests \
            python3-zstandard \
            subversion \
            wayland-protocols \
            xz-utils \
            --no-install-recommends --yes
      - run: echo /opt/vrm/lib | sudo tee /etc/ld.so.conf.d/vrm.conf
      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        id: cache
        with:
          path: benchmark-dependencies.tar.gz
          # key: benchmark-dependencies-${{ runner.os }}-${{ hashFiles('.github/workflows/benchmark.yml', 'tools/install_ci_codspeed_dependencies.sh') }}
          key: benchmark-dependencies-debug-2
      - if: steps.cache.outputs.cache-hit == 'true'
        run: tar xzf benchmark-dependencies.tar.gz -C /opt
      - if: steps.cache.outputs.cache-hit != 'true'
        run: sudo --preserve-env=GITHUB_ENV ./tools/install_ci_codspeed_dependencies.sh
      - run: sudo ldconfig
      - run: |
          python3 -m venv --system-site-packages .venv
          . ./.venv/bin/activate
          pip3 install "pytest < 9" "pytest-codspeed < 5"
          export PYTHONPATH="${PWD}/src:/opt/vrm/lib/python3.12/site-packages"
          echo "PYTHONPATH=${PYTHONPATH}" >>"$GITHUB_ENV"
          python3 -c 'import bpy; assert(bpy.app.version == (4, 5, 3))'
      - uses: CodSpeedHQ/action@6b43a0cd438f6ca5ad26f9ed03ed159ed2df7da9 # v4.1.1
        with:
          mode: instrumentation
          # run: . ../.venv/bin/activate && pytest --codspeed
          # run: . ../.venv/bin/activate; pytest --codspeed src/io_scene_vrm_benchmarks/mtoon1_auto_setup_benchmark_test.py src/io_scene_vrm_benchmarks/nop_test.py
          run: . ../.venv/bin/activate; pytest --codspeed src/io_scene_vrm_benchmarks/nop_test.py
          working-directory: benchmarks
