name: readme-update

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: |
          set -x

          git fetch --depth=1 origin main website README

          mkdir readme
          cd readme
          cp -fr ../.git .git
          git checkout README
          cp -fr ../.github .
          rm .github/workflows/gh-pages.yml
          rm .github/workflows/test.yml
          rm .github/workflows/release.yml
          cp ../README.md .
          git add .
          if git diff --cached --exit-code; then
            exit 0
          fi
          git status

          git config --global user.email "isamu@leafytree.jp"
          git config --global user.name "[BOT] Isamu Mogi"
          git commit -m "[BOT] Update README"

          case "$GITHUB_SHA" in
            "$(git rev-parse origin/main)");;
            "$(git rev-parse origin/website)");;
            *) exit 0;;
          esac

          git push origin README
