name: release

on:
  push:
    tags:
      - '*_*_*'

jobs:
  release:
    runs-on: ubuntu-22.04
    container:
      image: debian:bullseye
    steps:
      - name: Install package
        run: |
          apt-get update -qq
          apt-get dist-upgrade -y
          apt-get install -y advancecomp blender curl git python3 python3-numpy ruby shellcheck
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
          path: repo # Add "repo" to prevent "fatal: detected dubious ownership in repository at '...'"
      - name: Release
        run: cd repo && ./scripts/release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
